name: Deploy Lambdas to AWS
description: Deploy Lambda functions to AWS.

inputs:
  lambdas:
    description: 'List of Lambda function names to deploy'
    required: true
    default: 'lambda1,lambda2,lambda3'
env:
      INPUT_LAMBDAS: ${{ inputs.lambdas }}
runs:
  using: composite
  shell: bash
  run: |
  IFS=',' read -ra lambda_names <<< "$INPUT_LAMBDAS"

  for lambda_name in "${lambda_names[@]}"; do
    echo "Deploying Lambda: $lambda_name"
    # Your Lambda deployment logic here
  done
