name: POC to test loop in shell

on:
  workflow_dispatch
      
concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  poc-loop:
    name: POC to test loop in shell
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: deploy
        shell: bash
        run: |
          lambda_names=("lambda1" "lambda2" "lambda3") 
          for lambda_name in "${lambda_names[@]}"; do
            echo "Deploying Lambda: $lambda_name"
            # Your Lambda deployment logic here
          done
      
